---
- name: Install HTTP server
  hosts: g3
  become: yes

  tasks:
  - name: Install HTTP
    dnf:
      name: httpd
      state: present
    when: ansible_distribution == "Amazon"
   
  - name: Start HTTPD
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Amazon"

  - name: Enable HTTPD
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "Amazon"
  
  - name: Install Apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"
   
  - name: Start Apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: Enable Apache2
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install HTTP on CentOS
    yum:
      name: httpd
      state: present
    when: "ansible_facts['distribution'] in ['CentOS']"

  - name: Start HTTPD
    service:
      name: "{{ 'httpd' }}"
      state: started
...